apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  MAAS_HOST: maas.apps.ocp.5c5rv.sandbox634.opentlc.com
  MAAS_ENDPOINT_OVERRIDE: https://maas.apps.ocp.5c5rv.sandbox634.opentlc.com/rhoai-playground/qwen3-8b
