apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: authorino
  namespace: kuadrant-system
spec:
  listener:
    tls:
      enabled: true
      certSecretRef:
        name: authorino-server-cert
